export const skills = [
  "Software Development",
  "Data Science",
  "Product Management",
  "UI/UX Design",
  "Sales",
  "Marketing",
  "Finance",
  "Operations",
  "Business Development",
  "Customer Success",
  "Cybersecurity",
  "Cloud Architecture",
  "AI/ML Engineering",
  "Fundraising",
  "HR & Team Building",
  "Legal & Compliance",
  "Supply Chain",
  "Manufacturing",
  "Research & Development",
  "Content Creation",
];

export const industries = [
  "SaaS",
  "Fintech",
  "Healthcare",
  "E-commerce",
  "Edtech",
  "AI/ML",
  "Cybersecurity",
  "Blockchain",
  "Clean Energy",
  "Biotech",
  "Consumer Apps",
  "Hardware",
  "IoT",
  "Enterprise Software",
  "Marketplace",
  "Media & Entertainment",
  "Real Estate Tech",
  "Social Impact",
  "Gaming",
  "Travel & Hospitality",
];

export const locationArray = [
  "Remote only",
  "Hybrid (specific location)",
  "In-person (specific location)",
  "US - West Coast",
  "US - East Coast",
  "US - Midwest",
  "US - South",
  "Canada",
  "Europe",
  "Asia",
  "Latin America",
  "Africa",
  "Australia/Oceania",
  "Global/No preference",
];

export const founderStatusArray = [
  "First-time Founder",
  "Serial Entrepreneur",
  "Experienced Founder (1 previous venture)",
  "Corporate Executive transitioning to startup",
  "Technical Co-founder in previous venture",
];

export const financialContributionArray = [
  "No personal investment, seeking external funding",
  "Will self-fund/bootstrap",
  "Can invest <$25K personally",
  "Can invest $25K-$100K personally",
  "Can invest >$100K personally",
  "Brings existing investor relationships",
  "Prefers not to discuss until later stage",
  "Seeking co-founder with investment capability",
  "Open to sweat equity arrangements",
];
